services:
  spark-base:
    build: .
    image: custom-spark-image
    # Цей сервіс не запускається
    entrypoint: ["false"]

  spark-master:
    image: custom-spark-image
    container_name: spark-master
    ports:
      - "8088:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
  spark-worker-1:
    image: custom-spark-image
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  spark-worker-2:
    image: custom-spark-image
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077